sharpWave is distributed under the MIT License (MIT); this file is part of.
#
# Copyright (c) 2008-2021 Christian (graetz23@gmail.com)
#
# see LICENSE
#
# travis-ci.org builds after pushing to github.com
#
sudo: false

language: csharp

mono:
   - latest

os:
  - linux
#  - osx

script: make
